[package]
name = "tree-sitter-ouo"
description = "Tree-sitter parser for ouo"
version = "0.1.0"
authors = ["Anatoly Titov"]
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "ouo"]
categories = ["parser-implementations", "parsing", "text-editors"]
repository = "https://github.com/teatov/tree-sitter-ouo"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
  "tree-sitter.json",
  "/LICENSE",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.26.6"
